from .nodes.NDBoxUploadFile import NODE_CLASS_MAPPINGS as UPLOAD_NODE_CLASS_MAPPINGS
from .nodes.NDBoxUploadFile import NODE_DISPLAY_NAME_MAPPINGS as UPLOAD_NODE_DISPLAY_NAME_MAPPINGS
from .nodes.NDBoxDownloadFile import NODE_CLASS_MAPPINGS as DOWNLOAD_NODE_CLASS_MAPPINGS
from .nodes.NDBoxDownloadFile import NODE_DISPLAY_NAME_MAPPINGS as DOWNLOAD_NODE_DISPLAY_NAME_MAPPINGS


NODE_CLASS_MAPPINGS = {
    **UPLOAD_NODE_CLASS_MAPPINGS,
    **DOWNLOAD_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **UPLOAD_NODE_DISPLAY_NAME_MAPPINGS,
    **DOWNLOAD_NODE_DISPLAY_NAME_MAPPINGS,
}

# Expose frontend assets under /extensions/ComfyUI-Sundaybox/
WEB_DIRECTORY = "web"
